### ISSUE TITLE
.php files and images

### ISSUE THREAD

**Issue by christianjavan** [williambeto/generator-p4#1]
When I use a .php file instead of an .html file and images exist in folder /images, this error pops up when doing grunt publish:

Running "newer-postrun:imagemin:target:1:C:\xampp\htdocs\sitios\christianjavan\node_modules\grunt-newer\.cache" (newer-postrun) task
>> No "concat" targets found.
Warning: Task "concat" failed. Use --force to continue.

Additional  errors pop when using --force:

>> No "cssmin" targets found.
Warning: Task "cssmin" failed. Used --force, continuing.
>> No "uglify" targets found.
Warning: Task "uglify" failed. Used --force, continuing.

Any idea how to solve this?

**Comment by williambeto** [comment]
@christianjavan 
You can use .php files in your project, but must be a index.html file with the settings of 'usemin'

in  index.html file:

`
<script src="/assets/js/foo.js"></script>
<script src="/assets/js/bar.js"></script>
`

in  other-file.php file:

`
<script src="/assets/js/foo.js"></script>
<script src="/assets/js/bar.js"></script>
`

Read more about `[grunt-usemin](https://github.com/yeoman/grunt-usemin)
